### ISSUE TITLE
Notification appears only for a very short time

### ISSUE THREAD

**Issue by silberzwiebel** [neumann89/ShutdownTimer#10]
Hi, it's me again ;)

if I enable the shutdown timer, a notification pops up in the middle of the screen. But it can be seen for a very short time only, barely enough time to read it at all. Could you make that duration longer?

Thanks,
silberzwiebel

**Comment by neumann89** [comment]
Right it was a bit too short. I changed the duration from 2 to 4 seconds.
Closed by #448e9823aaf37357846228047e6542a796a09c05
