### ISSUE TITLE
Stylesheet issue

### ISSUE THREAD

**Issue by zagortenay333** [neumann89/ShutdownTimer#16]
Please don't add the default style classes into the extension stylesheet; themes cannot override it.
On top of that, other extension get broken because they inherit styles from this part of the aggregate menu.
![t2](https://cloud.githubusercontent.com/assets/11144630/8146032/e90ab216-1222-11e5-99a0-9fd24986b91d.png)
Open Weather extension gets broken on light themes:
![t](https://cloud.githubusercontent.com/assets/11144630/8146033/f8b7d266-1222-11e5-914b-06fd68ba0bce.png)

**Comment by neumann89** [comment]
Oh right, thank you for this detailed issue :+1:

**Comment by neumann89** [comment]
Closed by c3896e68f903636f405a631f71426b64262bc779
