### ISSUE TITLE
Add spanish language support

### ISSUE THREAD

**Issue by jesusignazio** [neumann89/ShutdownTimer#2]
Hi. I'm interested in help you translating the locale files to add support to the spanish language.
Thanks.

**Comment by neumann89** [comment]
Hi @jesusignazio , thanks for your message and volition to help!
I created a file /ShutdownTimer@neumann/locale/es/LC_MESSAGES/ShutdownTimer.po
for spain translation. There you can add the spanish strings and your name/email as translator if you want.
Best regards

**Comment by neumann89** [comment]
done with #5
