### ISSUE TITLE
extension gets not enabled

### ISSUE THREAD

**Issue by silberzwiebel** [neumann89/ShutdownTimer#9]
Hi,

I've updated your extension via the official GNOME shell extension homepage but it fails to get activated. It worked fine before the update. Unfortunately I do not know where I could for a error log, maybe you know? I'm using Fedora 21 with GNOME Shell 3.14.4.
Let me know how I can provide useful information to you.

Thanks,
silberzwiebel

**Comment by neumann89** [comment]
Thanks for this bug report I will check this issue tomorrow. You can press Alt+F2 and type lg + Enter to open the shell console where you can see error logs for this extension.

**Comment by neumann89** [comment]
Tried it on Ubuntu GNOME 15.04 (GNOME 3.14 version too) some minutes ago and it worked to activate it from extension homepage.
I will try it on Fedora too next time.

**Comment by silberzwiebel** [comment]
It seemed to be an update issue. I've deleted the (empty) extension folder from ~/.local/share/gnome-shell/extensions/ and re-installed from the extensions website and now it works. Maybe something got wrong while updating and this seems to be more an issue for the GNOME website than for you...
